#!/bin/bash

set -euo pipefail

screenshot_dir=$HOME
command -v xdg-user-dir > /dev/null \
  && screenshot_dir=$(xdg-user-dir PICTURES)

usage() {
  printf >&2 'usage: printscreen {full|region}\n'
}

command=${1:-}

filename=$(date +"%Y-%m-%dT%H%M%S%z").png
mkdir -p "$screenshot_dir"

case $command in
full)
  focused_output=$(
    swaymsg -t get_tree \
      | jq -r '
        .nodes[]
        | select([recurse(.nodes[]?, .floating_nodes[]?) | .focused ] | any)
        | .name
      '
  )
  grim -c -o "$focused_output" "$screenshot_dir/$filename"
  ;;
region)
  slurp | grim -g - "$screenshot_dir/$filename"
  ;;
*)
  usage
  exit 1
  ;;
esac
