# shellcheck shell=bash

post_install() {
  /usr/lib/kit-base-system/render-crypttab-initramfs
  /usr/lib/kit-base-system/render-fstab

  echo "Services are enabled by preset on first boot. On an existing system,"
  echo "apply the preset and reboot:"
  echo ""
  echo "  sudo systemctl preset iwd systemd-networkd systemd-oomd \\"
  echo "    systemd-resolved systemd-timesyncd tlp"
}

post_upgrade() {
  /usr/lib/kit-base-system/render-crypttab-initramfs
  /usr/lib/kit-base-system/render-fstab
}
